#!/usr/bin/env bash
#
# Token Foundry — create the deployment Service Principal for 方案 A, with the
# EXACT role set the GitHub Action's hub terraform needs, in one shot.
#
# 方案 A runs each per-account GitModel hub's terraform inside the GitHub Action
# `deploy-hub.yml`, authenticated as a Service Principal (SP). That SP needs a
# specific bundle of roles; granting them by hand is error-prone and easy to
# under-provision (a missing Storage Blob Data Contributor silently breaks
# `terraform init` against the remote state, a missing User Access Administrator
# breaks the hub's identity role assignments). This script creates the SP (or
# reuses an existing one) and assigns all of them idempotently.
#
# ROLES GRANTED (mirrors the working dev-001 SP `tokenfoundry-hub-deployer-sp`):
#
#   role                             scope                     why
#   ------------------------------   -----------------------   -------------------------------
#   Contributor                      subscription              terraform creates a NEW resource
#                                                              group + Container App/env/etc per
#                                                              hub account (RG name isn't known
#                                                              ahead of time -> sub scope).
#   User Access Administrator        subscription              terraform assigns roles to each
#                                                              hub's managed identity (ACR pull,
#                                                              KV read). Granting roles needs UAA.
#                                                              *** HIGH PRIVILEGE — see note ***
#   Key Vault Secrets User           the env's Key Vault        Action reads the control plane's
#                                                              per-account `gh-<id>-jobinput`
#                                                              secret (oauth/admin/hubkey).
#   Storage Blob Data Contributor    the env's tfstate storage  terraform reads+writes the remote
#                                                              state blob (hubs/<id>.tfstate).
#
# NOTE on User Access Administrator: this lets the SP grant roles, which is
# powerful. It's required because the hub terraform wires each hub's identity to
# ACR/KV via azurerm_role_assignment. If your security posture forbids UAA on the
# deployer, pass --no-uaa and instead pre-create the hub identities + role
# assignments out-of-band (not currently automated). Default: UAA IS granted, to
# match the proven dev-001 setup.
#
# Secrets: the SP password is generated by Azure. This script writes the full SP
# cred set (client-id / client-secret / tenant-id / subscription-id) into the
# environment's Key Vault as `deployer-sp-*` secrets, so the Token Foundry Portal
# (GitHub Accounts -> Deploy configuration) can read them back and push them to
# the repo automatically (no manual copy/paste). The password is also printed
# ONCE as a convenience.
#
#   ⚠️ SECURITY TRADE-OFF (方案 A): storing the SP creds in Key Vault means the
#   control plane's managed identity (Key Vault Secrets Officer on this vault) can
#   READ them. That relaxes 方案 A's original isolation ("control plane can't
#   reach the SP"): a compromised control plane could now read a subscription-wide
#   Contributor + User Access Administrator SP. This is a deliberate choice to get
#   a fully-automated deploy → create-sp → setup chain. To restore isolation
#   later, stop writing to KV here and pass the creds via env/eval instead.
#
# Usage:
#   az login && az account set --subscription <id>
#   ./scripts/create-deployer-sp.sh -g tokenfoundry-rg-dev-001
#   ./scripts/create-deployer-sp.sh -g <rg> -n my-deployer-sp        # custom name
#   ./scripts/create-deployer-sp.sh -g <rg> --reset-password         # rotate a existing SP's secret
#   ./scripts/create-deployer-sp.sh -g <rg> --no-uaa                 # skip User Access Administrator
#
# Options:
#   -g <rg>            (required) resource group of the target environment (to
#                      resolve its Key Vault + tfstate storage account).
#   -n <name>          SP display name (default: tokenfoundry-hub-deployer-sp-<env>,
#                      derived from the RG so each environment gets its own SP).
#   --reset-password   reset the SP's client secret even if the SP already exists
#                      (prints a fresh ARM_CLIENT_SECRET).
#   --no-uaa           do NOT grant User Access Administrator (see NOTE above).
#   -h                 help.
#
# Prereqs: `az login` with rights to create SPs (Application Administrator or
# Owner) and to assign roles (Owner or User Access Administrator) at the
# subscription. Idempotent: re-running reconciles the role set.

set -euo pipefail

log()  { printf '\n\033[1;36m>>> %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m%s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

usage() { sed -n '2,64p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# --- args ---
RG=""
SP_NAME=""   # default derived from the RG below (per-environment, see note)
RESET_PW=false
GRANT_UAA=true
while [[ $# -gt 0 ]]; do
  case "$1" in
    -g) RG="${2:-}"; shift 2 ;;
    -n) SP_NAME="${2:-}"; shift 2 ;;
    --reset-password) RESET_PW=true; shift ;;
    --no-uaa) GRANT_UAA=false; shift ;;
    -h|--help) usage 0 ;;
    *) die "unknown argument: $1 (use -h for help)" ;;
  esac
done

# --- preflight: tools + auth ---
command -v az >/dev/null || die "az CLI not found"
az account show >/dev/null 2>&1 || die "Not logged in to Azure. Run: az login"
[[ -n "$RG" ]] || die "resource group is required: -g <rg>"
az group show -n "$RG" >/dev/null 2>&1 || die "resource group '$RG' not found (or no access)"

# Default the SP name to a PER-ENVIRONMENT one derived from the RG's env suffix
# (e.g. tokenfoundry-rg-dev-a10 -> tokenfoundry-hub-deployer-sp-dev-a10). A single
# shared SP name across environments is a footgun: the SECOND environment finds
# the SP already exists, skips secret generation (without --reset-password), and
# writes an EMPTY client-secret to its Key Vault — breaking that env's deploy
# config (sp_creds_present=false). One SP per env avoids the collision entirely.
if [[ -z "$SP_NAME" ]]; then
  ENV_SUFFIX="${RG#tokenfoundry-rg-}"   # dev-a10  (falls back to full RG if no match)
  SP_NAME="tokenfoundry-hub-deployer-sp-${ENV_SUFFIX}"
fi

SUB_ID="$(az account show --query id -o tsv)"
SUB_SCOPE="/subscriptions/${SUB_ID}"

# --- resolve the env's Key Vault + tfstate storage account ---
log "Resolving Key Vault + tfstate storage account in $RG"
KV_NAME="$(az keyvault list -g "$RG" --query '[0].name' -o tsv 2>/dev/null || true)"
TFSTATE_SA="$(az storage account list -g "$RG" --query "[?contains(name,'tfstate')].name | [0]" -o tsv 2>/dev/null || true)"
[[ -n "$KV_NAME"    ]] || die "could not find a Key Vault in $RG"
[[ -n "$TFSTATE_SA" ]] || die "could not find a tfstate storage account in $RG (name containing 'tfstate')"
KV_ID="$(az keyvault show -n "$KV_NAME" --query id -o tsv)"
SA_ID="$(az storage account show -g "$RG" -n "$TFSTATE_SA" --query id -o tsv)"
printf '  subscription   : %s\n' "$SUB_ID"
printf '  Key Vault      : %s\n' "$KV_NAME"
printf '  tfstate SA     : %s\n' "$TFSTATE_SA"
printf '  SP name        : %s\n' "$SP_NAME"

# --- 1. create (or reuse) the SP ---
# We do NOT use `az ad sp create-for-rbac --role ... --scopes ...` because it only
# takes one role/scope pair and we need four. Instead: ensure the app+SP exist,
# (re)set a password when needed, then assign roles explicitly below.
APP_ID="$(az ad app list --display-name "$SP_NAME" --query '[0].appId' -o tsv 2>/dev/null || true)"
CLIENT_SECRET=""
if [[ -z "$APP_ID" ]]; then
  log "Creating app registration + Service Principal '$SP_NAME'"
  APP_ID="$(az ad app create --display-name "$SP_NAME" --query appId -o tsv)"
  az ad sp create --id "$APP_ID" --output none
  # Fresh credential for a brand-new SP.
  CLIENT_SECRET="$(az ad app credential reset --id "$APP_ID" \
    --display-name "hub-deployer" --years 1 --query password -o tsv)"
  ok "SP created (appId=$APP_ID)"
else
  ok "SP '$SP_NAME' already exists (appId=$APP_ID)"
  # Ensure the SP object exists for this app (app can exist without an SP).
  az ad sp show --id "$APP_ID" >/dev/null 2>&1 || az ad sp create --id "$APP_ID" --output none
  # Self-heal: if THIS env's Key Vault has no usable client-secret (empty or
  # missing), we MUST mint one now even without --reset-password. Otherwise the
  # secret block below keeps the empty value and the env's deploy config never
  # goes Ready. This is the exact failure hit on dev-a10 (a reused SP left the
  # KV client-secret empty). The stored secret is per-vault, so a fresh env
  # always needs its own.
  KV_SECRET_EXISTING="$(az keyvault secret show --vault-name "$KV_NAME" \
    --name deployer-sp-client-secret --query value -o tsv 2>/dev/null || true)"
  if [[ "$RESET_PW" != true && -z "$KV_SECRET_EXISTING" ]]; then
    warn "no usable deployer-sp-client-secret in $KV_NAME — forcing a reset so this env can deploy"
    RESET_PW=true
  fi
  if [[ "$RESET_PW" == true ]]; then
    log "Resetting client secret"
    CLIENT_SECRET="$(az ad app credential reset --id "$APP_ID" \
      --display-name "hub-deployer" --years 1 --query password -o tsv)"
    ok "client secret reset"
  fi
fi

SP_OID="$(az ad sp show --id "$APP_ID" --query id -o tsv)"
[[ -n "$SP_OID" ]] || die "could not resolve SP object id for appId $APP_ID"

# --- 2. assign the role bundle (idempotent) ---
# Helper: assign a role at a scope, tolerating "already exists".
grant() { # $1=role  $2=scope  $3=label
  az role assignment create \
    --assignee-object-id "$SP_OID" \
    --assignee-principal-type ServicePrincipal \
    --role "$1" --scope "$2" --output none 2>/dev/null \
    && ok "granted: $3" \
    || warn "already present or insufficient perms: $3 (verify manually)"
}

log "Assigning roles to the SP"
grant "Contributor"                   "$SUB_SCOPE" "Contributor @ subscription"
if [[ "$GRANT_UAA" == true ]]; then
  grant "User Access Administrator"   "$SUB_SCOPE" "User Access Administrator @ subscription"
else
  warn "SKIPPED User Access Administrator (--no-uaa): hub identity role assignments will FAIL unless pre-created out-of-band"
fi
grant "Key Vault Secrets User"        "$KV_ID"     "Key Vault Secrets User @ $KV_NAME"
grant "Storage Blob Data Contributor" "$SA_ID"     "Storage Blob Data Contributor @ $TFSTATE_SA"

# --- 3. persist SP creds to Key Vault (方案 A: setup reads them back) ---
# The non-secret ids (client/tenant/subscription) are safe to (re)write every
# run. The client SECRET is only known right after create / --reset-password;
# writing an empty value would CLOBBER a valid stored secret, so we only write it
# when we actually generated one this run.
log "Writing SP creds to Key Vault $KV_NAME (deployer-sp-*)"
TENANT_ID="$(az account show --query tenantId -o tsv)"
kv_set() { # $1=name $2=value
  az keyvault secret set --vault-name "$KV_NAME" --name "$1" --value "$2" --output none \
    && ok "KV secret set: $1" \
    || die "failed to write $1 to KV (need Key Vault Secrets Officer on $KV_NAME)"
}
kv_set "deployer-sp-client-id"       "$APP_ID"
kv_set "deployer-sp-tenant-id"       "$TENANT_ID"
kv_set "deployer-sp-subscription-id" "$SUB_ID"
if [[ -n "$CLIENT_SECRET" ]]; then
  kv_set "deployer-sp-client-secret" "$CLIENT_SECRET"
else
  warn "client secret NOT written (SP pre-existed, no --reset-password) — the existing"
  warn "  deployer-sp-client-secret in KV is kept. Pass --reset-password to rotate it."
fi

# --- 4. report ---
log "Done. Service Principal is ready for 方案 A (creds stored in Key Vault)."
printf '  ARM_CLIENT_ID        : %s\n' "$APP_ID"
printf '  ARM_TENANT_ID        : %s\n' "$TENANT_ID"
printf '  ARM_SUBSCRIPTION_ID  : %s\n' "$SUB_ID"
if [[ -n "$CLIENT_SECRET" ]]; then
  printf '\n\033[1;33m  ARM_CLIENT_SECRET (also stored in KV; shown ONCE):\033[0m\n'
  printf '  %s\n' "$CLIENT_SECRET"
fi
printf '\n  SP creds are in Key Vault (deployer-sp-*). Final step is in the Token\n'
printf '  Foundry Portal — GitHub Accounts -> Deploy configuration: paste the two\n'
printf '  GitHub PATs. The Portal reads these SP creds from KV and pushes them to\n'
printf '  the repo automatically (no shell script needed).\n'
